# Generated by Django 6.0 on 2026-01-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='credits',
            field=models.FloatField(default=0.0),
        ),
    ]
