# Generated by Django 6.0 on 2026-02-25 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profilelink_profilepageview_profilelinkclick'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, max_length=200)),
                ('utm_medium', models.CharField(blank=True, max_length=200)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('utm_term', models.CharField(blank=True, max_length=200)),
                ('utm_content', models.CharField(blank=True, max_length=200)),
                ('referrer', models.URLField(blank=True, max_length=2000)),
                ('referrer_domain', models.CharField(blank=True, max_length=253)),
                ('landing_page', models.CharField(blank=True, max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Acquisition',
                'verbose_name_plural': 'User Acquisitions',
            },
        ),
    ]
