# Generated by Django 6.0 on 2026-01-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['order', 'price_monthly']},
        ),
        migrations.RemoveField(
            model_name='plan',
            name='quiz_limit',
        ),
        migrations.AddField(
            model_name='plan',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
