# Generated by Django 6.0 on 2026-01-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subscription_usage_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('banner_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('danger', 'Danger'), ('promo', 'Promotional')], default='info', max_length=20)),
                ('link_url', models.URLField(blank=True, help_text='Optional link for CTA button')),
                ('link_text', models.CharField(blank=True, help_text="Button text (e.g., 'Learn More')", max_length=50)),
                ('display_seconds', models.PositiveIntegerField(default=5, help_text='Seconds to display before switching to next banner')),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissible', models.BooleanField(default=True, help_text='Allow users to close the banner')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
