# Generated by Django 6.0 on 2026-01-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_banner_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='pricing_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
