# Generated by Django 6.0 on 2026-02-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_pricing_data_to_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='display_mode',
            field=models.CharField(choices=[('banner', 'Top Banner'), ('popup', 'Popup Modal'), ('both', 'Both')], default='banner', help_text='Where to display this banner', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_s3_key',
            field=models.CharField(blank=True, help_text='S3 key for cleanup', max_length=500),
        ),
        migrations.AddField(
            model_name='banner',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL (uploaded via admin)'),
        ),
    ]
