# Generated by Django 6.0 on 2026-02-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_banner_display_mode_and_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='requires_auth',
            field=models.BooleanField(default=False, help_text='Only show to logged-in users'),
        ),
    ]
