# Generated by Django 6.0 on 2026-02-20 09:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_banner_requires_auth'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Table 'roleplay_credittransaction' already exists from the roleplay app.
        # Use SeparateDatabaseAndState to register the model in core's state
        # without recreating the table.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CreditTransaction',
                    fields=[
                        ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        ('credits', models.IntegerField(help_text='Number of credits purchased')),
                        ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                        ('currency', models.CharField(default='INR', max_length=3)),
                        ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                        ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                        ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                        ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'verbose_name': 'Credit Transaction',
                        'verbose_name_plural': 'Credit Transactions',
                        'db_table': 'roleplay_credittransaction',
                        'ordering': ['-created_at'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
