# Generated by Django 6.0 on 2026-02-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_credittransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkRedirectEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(max_length=2000)),
                ('target_domain', models.CharField(blank=True, max_length=253)),
                ('ip_hash', models.CharField(max_length=64)),
                ('referrer', models.URLField(blank=True, max_length=2000)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Time spent on page in milliseconds before leaving', null=True)),
                ('clicked', models.BooleanField(default=False, help_text='Whether the user clicked "Go to Link"')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Link Redirect Event',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_domain', 'created_at'], name='core_linkre_target__f96f9e_idx')],
            },
        ),
    ]
