# Generated by Django 6.0 on 2026-01-07 17:01

from django.db import migrations


def create_default_templates(apps, schema_editor):
    VideoTemplate = apps.get_model('quiz', 'VideoTemplate')

    templates = [
        {
            'name': 'Dark Purple',
            'slug': 'dark-purple',
            'description': 'Classic dark theme with purple accents',
            'is_default': True,
            'is_premium': False,
            'sort_order': 1,
            'config': {
                'colors': {
                    'bg_color': [18, 18, 18],
                    'text_color': [255, 255, 255],
                    'accent_color': [138, 43, 226],
                    'correct_color': [0, 200, 83],
                    'wrong_color': [239, 68, 68],
                    'option_bg': [38, 38, 38],
                    'option_text': [240, 240, 240],
                    'timer_bg': [75, 0, 130],
                    'muted_text': [156, 163, 175],
                    'card_bg': [28, 28, 30]
                }
            }
        },
        {
            'name': 'Clean Light',
            'slug': 'clean-light',
            'description': 'Bright and professional white theme',
            'is_default': False,
            'is_premium': True,
            'sort_order': 2,
            'config': {
                'colors': {
                    'bg_color': [250, 250, 250],
                    'text_color': [30, 30, 30],
                    'accent_color': [59, 130, 246],
                    'correct_color': [34, 197, 94],
                    'wrong_color': [239, 68, 68],
                    'option_bg': [255, 255, 255],
                    'option_text': [30, 30, 30],
                    'timer_bg': [59, 130, 246],
                    'muted_text': [107, 114, 128],
                    'card_bg': [255, 255, 255]
                }
            }
        },
        {
            'name': 'Neon Glow',
            'slug': 'neon-glow',
            'description': 'Vibrant neon colors on dark background',
            'is_default': False,
            'is_premium': True,
            'sort_order': 3,
            'config': {
                'colors': {
                    'bg_color': [10, 10, 20],
                    'text_color': [255, 255, 255],
                    'accent_color': [0, 255, 255],
                    'correct_color': [0, 255, 128],
                    'wrong_color': [255, 0, 128],
                    'option_bg': [20, 20, 40],
                    'option_text': [255, 255, 255],
                    'timer_bg': [255, 0, 255],
                    'muted_text': [150, 150, 180],
                    'card_bg': [15, 15, 35]
                }
            }
        },
        {
            'name': 'Sunset',
            'slug': 'sunset',
            'description': 'Warm orange and red tones',
            'is_default': False,
            'is_premium': True,
            'sort_order': 4,
            'config': {
                'colors': {
                    'bg_color': [30, 20, 30],
                    'text_color': [255, 255, 255],
                    'accent_color': [255, 100, 50],
                    'correct_color': [100, 255, 100],
                    'wrong_color': [255, 80, 80],
                    'option_bg': [50, 30, 40],
                    'option_text': [255, 255, 255],
                    'timer_bg': [255, 150, 50],
                    'muted_text': [200, 180, 180],
                    'card_bg': [40, 25, 35]
                }
            }
        },
        {
            'name': 'Ocean Blue',
            'slug': 'ocean-blue',
            'description': 'Deep blue and teal colors',
            'is_default': False,
            'is_premium': True,
            'sort_order': 5,
            'config': {
                'colors': {
                    'bg_color': [10, 25, 47],
                    'text_color': [255, 255, 255],
                    'accent_color': [0, 200, 200],
                    'correct_color': [0, 230, 118],
                    'wrong_color': [255, 107, 107],
                    'option_bg': [20, 40, 70],
                    'option_text': [255, 255, 255],
                    'timer_bg': [0, 150, 180],
                    'muted_text': [150, 180, 200],
                    'card_bg': [15, 35, 60]
                }
            }
        },
    ]

    for template_data in templates:
        VideoTemplate.objects.create(**template_data)


def remove_default_templates(apps, schema_editor):
    VideoTemplate = apps.get_model('quiz', 'VideoTemplate')
    slugs = ['dark-purple', 'clean-light', 'neon-glow', 'sunset', 'ocean-blue']
    VideoTemplate.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_videotemplate'),
    ]

    operations = [
        migrations.RunPython(create_default_templates, remove_default_templates),
    ]
