# Generated by Django 6.0 on 2026-01-07 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_create_default_video_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkvideojob',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_jobs', to='quiz.videotemplate'),
        ),
    ]
