# Generated by Django 6.0 on 2026-01-18 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_topic_approved_at_topic_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('single', 'Single Video'), ('bulk_item', 'Bulk Video Item')], default='single', max_length=20)),
                ('bulk_group_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('task_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('question_ids', models.JSONField(default=list)),
                ('questions_data', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percent', models.IntegerField(default=0)),
                ('progress_message', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('post_to_instagram', models.BooleanField(default=False)),
                ('post_to_youtube', models.BooleanField(default=False)),
                ('instagram_caption', models.TextField(blank=True)),
                ('youtube_title', models.CharField(blank=True, max_length=200)),
                ('youtube_description', models.TextField(blank=True)),
                ('instagram_posted', models.BooleanField(default=False)),
                ('youtube_posted', models.BooleanField(default=False)),
                ('instagram_error', models.TextField(blank=True)),
                ('youtube_error', models.TextField(blank=True)),
                ('s3_url', models.URLField(blank=True, max_length=500)),
                ('s3_key', models.CharField(blank=True, max_length=255)),
                ('video_config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to='quiz.quiz')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_jobs', to='quiz.videotemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='quiz_videoj_user_id_2c90bb_idx'), models.Index(fields=['bulk_group_id'], name='quiz_videoj_bulk_gr_2ee2ae_idx')],
            },
        ),
    ]
