# Generated by Django 6.0 on 2026-01-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_add_videojob'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='youtube_tags',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
