# Generated by Django 6.0 on 2026-01-07 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePlayBot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('avatar_url', models.URLField(blank=True)),
                ('system_prompt', models.TextField(help_text='Instructions for the AI model')),
                ('voice', models.CharField(choices=[('alloy', 'Alloy'), ('echo', 'Echo'), ('fable', 'Fable'), ('onyx', 'Onyx'), ('nova', 'Nova'), ('shimmer', 'Shimmer')], default='alloy', max_length=20)),
                ('category', models.CharField(choices=[('interview', 'Interview Prep'), ('language', 'Language Learning'), ('education', 'Education'), ('therapy', 'Therapy & Counseling'), ('coaching', 'Life Coaching'), ('roleplay', 'General Roleplay'), ('other', 'Other')], default='roleplay', max_length=50)),
                ('custom_configuration', models.JSONField(blank=True, default=dict, help_text='Additional configuration like temperature, etc.')),
                ('required_credits', models.IntegerField(default=10, help_text='Credits required per minute')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Roleplay Bot',
                'verbose_name_plural': 'Roleplay Bots',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credits', models.IntegerField(help_text='Number of credits purchased')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Transaction',
                'verbose_name_plural': 'Credit Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleplaySession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('error', 'Error')], default='in_progress', max_length=20)),
                ('transcript', models.TextField(blank=True, help_text='Conversation transcript')),
                ('duration_seconds', models.IntegerField(default=0)),
                ('credits_used', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='roleplay.roleplaybot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roleplay_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Roleplay Session',
                'verbose_name_plural': 'Roleplay Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
