# Generated by Django 6.0 on 2026-01-19 17:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WordBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=10, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=20)),
                ('hint', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('used_as_daily', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='GameAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guesses', models.JSONField(default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_won', models.BooleanField(default=False)),
                ('attempts_used', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('daily_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.dailyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('user', 'daily_word')},
            },
        ),
        migrations.CreateModel(
            name='CodeWordVideoExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handle_name', models.CharField(blank=True, max_length=50)),
                ('template', models.CharField(default='default', max_length=50)),
                ('include_answer', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('video_s3_key', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameattempt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('total_games', models.IntegerField(default=0)),
                ('total_wins', models.IntegerField(default=0)),
                ('last_played_date', models.DateField(blank=True, null=True)),
                ('guess_distribution', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailyword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.wordbank'),
        ),
    ]
