# Generated by Django 6.0 on 2026-01-16 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='account_automation_enabled',
            field=models.BooleanField(default=False, help_text='Enable automation for comments on posts without specific automation rules'),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='account_comment_reply',
            field=models.TextField(blank=True, help_text='Default reply to comments (used when no post-level automation matches)'),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='account_followup_dm',
            field=models.TextField(blank=True, help_text='Default follow-up DM to send after comment reply'),
        ),
        migrations.CreateModel(
            name='InstagramAutomation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Name for this automation (e.g., 'Python Quiz Promo')", max_length=100)),
                ('instagram_post_id', models.CharField(blank=True, help_text='Instagram post ID (optional - leave blank for keyword-only matching)', max_length=255)),
                ('keywords', models.TextField(help_text="Comma-separated keywords to trigger this automation (e.g., 'link, send, dm')")),
                ('comment_reply', models.TextField(help_text='Reply text to post as a comment response')),
                ('followup_dm', models.TextField(help_text='Follow-up DM text to send to the commenter')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Automation',
                'verbose_name_plural': 'Instagram Automations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstagramCommentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('post_id', models.CharField(blank=True, max_length=255)),
                ('commenter_username', models.CharField(blank=True, max_length=255)),
                ('commenter_id', models.CharField(blank=True, max_length=255)),
                ('comment_text', models.TextField(blank=True)),
                ('comment_replied', models.BooleanField(default=False)),
                ('dm_sent', models.BooleanField(default=False)),
                ('reply_text', models.TextField(blank=True)),
                ('dm_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('replied', 'Replied'), ('dm_sent', 'DM Sent'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='received', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('automation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_events', to='instagram.instagramautomation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_comment_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instagram Comment Event',
                'verbose_name_plural': 'Instagram Comment Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
