# Generated by Django 6.0 on 2026-01-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_instagramaccount_account_automation_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='account_follow_request_message',
            field=models.TextField(blank=True, help_text='Message to send when user is not following (include call-to-action to follow)'),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='account_require_follow',
            field=models.BooleanField(default=False, help_text='Require user to follow before sending follow-up DM'),
        ),
        migrations.AddField(
            model_name='instagramautomation',
            name='follow_request_message',
            field=models.TextField(blank=True, help_text='Message to send when user is not following (include call-to-action to follow)'),
        ),
        migrations.AddField(
            model_name='instagramautomation',
            name='require_follow',
            field=models.BooleanField(default=False, help_text='Require user to follow before sending follow-up DM'),
        ),
        migrations.AddField(
            model_name='instagramcommentevent',
            name='pending_followup_dm',
            field=models.TextField(blank=True, help_text='DM text to send after user confirms they followed'),
        ),
        migrations.AddField(
            model_name='instagramcommentevent',
            name='waiting_for_follow',
            field=models.BooleanField(default=False, help_text="User hasn't followed yet, waiting for confirmation"),
        ),
        migrations.AlterField(
            model_name='instagramcommentevent',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('replied', 'Replied'), ('waiting_follow', 'Waiting for Follow'), ('dm_sent', 'DM Sent'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='received', max_length=20),
        ),
    ]
