# Generated by Django 6.0 on 2026-01-16 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0003_instagramaccount_account_follow_request_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcommentevent',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('received', 'Received'), ('processed', 'Processed'), ('replied', 'Replied'), ('waiting_follow', 'Waiting for Follow'), ('dm_sent', 'DM Sent'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='instagramcommentevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_comment_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
