# Generated by Django 6.0 on 2026-01-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_alter_instagramcommentevent_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramaccount',
            name='account_follow_request_message',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='account_require_follow',
        ),
        migrations.RemoveField(
            model_name='instagramautomation',
            name='follow_request_message',
        ),
        migrations.RemoveField(
            model_name='instagramautomation',
            name='require_follow',
        ),
        migrations.RemoveField(
            model_name='instagramcommentevent',
            name='pending_followup_dm',
        ),
        migrations.RemoveField(
            model_name='instagramcommentevent',
            name='waiting_for_follow',
        ),
        migrations.AlterField(
            model_name='instagramcommentevent',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('received', 'Received'), ('processed', 'Processed'), ('replied', 'Replied'), ('dm_sent', 'DM Sent'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='processing', max_length=20),
        ),
    ]
