# Generated by Django 6.0 on 2026-01-22 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0006_multiple_reply_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramcommentevent',
            name='automation',
        ),
        migrations.RemoveField(
            model_name='instagramcommentevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='account_automation_enabled',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='account_comment_replies',
        ),
        migrations.RemoveField(
            model_name='instagramaccount',
            name='account_followup_dms',
        ),
        migrations.CreateModel(
            name='DMFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name for this flow', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('trigger_type', models.CharField(choices=[('comment_keyword', 'Comment with Keyword'), ('comment_any', 'Any Comment')], default='comment_keyword', max_length=20)),
                ('instagram_post_id', models.CharField(blank=True, help_text='Instagram post ID (optional - leave blank for all posts)', max_length=255)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords to trigger this flow')),
                ('is_active', models.BooleanField(default=True)),
                ('total_triggered', models.PositiveIntegerField(default=0)),
                ('total_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DM Flow',
                'verbose_name_plural': 'DM Flows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order of this node in the flow (0 = first)')),
                ('node_type', models.CharField(choices=[('comment_reply', 'Comment Reply'), ('message_text', 'Text Message'), ('message_quick_reply', 'Quick Reply Message'), ('message_link', 'Link Message'), ('message_media', 'Media Message'), ('condition_follower', 'Follower Check'), ('collect_data', 'Collect Data'), ('delay', 'Delay')], max_length=30)),
                ('name', models.CharField(blank=True, help_text='Optional label for this step', max_length=100)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='instagram.dmflow')),
                ('next_node', models.ForeignKey(blank=True, help_text='Next node in the flow (for sequential flows)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_nodes', to='instagram.flownode')),
            ],
            options={
                'verbose_name': 'Flow Node',
                'verbose_name_plural': 'Flow Nodes',
                'ordering': ['flow', 'order'],
                'unique_together': {('flow', 'order')},
            },
        ),
        migrations.CreateModel(
            name='FlowSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_scoped_id', models.CharField(help_text='Instagram-scoped ID (IGSID) for DMs', max_length=255)),
                ('instagram_username', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting_reply', 'Waiting for Reply'), ('waiting_scheduled', 'Waiting for Scheduled Message'), ('completed', 'Completed'), ('expired', 'Expired'), ('error', 'Error')], default='active', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict)),
                ('trigger_comment_id', models.CharField(blank=True, help_text='Comment ID that triggered this flow', max_length=255)),
                ('trigger_post_id', models.CharField(blank=True, max_length=255)),
                ('trigger_comment_text', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sessions', to='instagram.flownode')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='instagram.dmflow')),
            ],
            options={
                'verbose_name': 'Flow Session',
                'verbose_name_plural': 'Flow Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('flow_started', 'Flow Started'), ('node_executed', 'Node Executed'), ('message_sent', 'Message Sent'), ('comment_replied', 'Comment Replied'), ('quick_reply_received', 'Quick Reply Received'), ('text_reply_received', 'Text Reply Received'), ('condition_checked', 'Condition Checked'), ('data_collected', 'Data Collected'), ('delay_scheduled', 'Delay Scheduled'), ('flow_completed', 'Flow Completed'), ('error', 'Error')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution_logs', to='instagram.flownode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='instagram.flowsession')),
            ],
            options={
                'verbose_name': 'Flow Execution Log',
                'verbose_name_plural': 'Flow Execution Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollectedLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_scoped_id', models.CharField(max_length=255)),
                ('instagram_username', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Any extra fields collected')),
                ('is_follower', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Account owner who collected this lead', on_delete=django.db.models.deletion.CASCADE, related_name='collected_leads', to=settings.AUTH_USER_MODEL)),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_leads', to='instagram.dmflow')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_leads', to='instagram.flowsession')),
            ],
            options={
                'verbose_name': 'Collected Lead',
                'verbose_name_plural': 'Collected Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickReplyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Button text (max 20 chars)', max_length=20)),
                ('payload', models.CharField(help_text='Identifier for this option', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_reply_options', to='instagram.flownode')),
                ('target_node', models.ForeignKey(blank=True, help_text='Node to execute when this button is clicked', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_quick_replies', to='instagram.flownode')),
            ],
            options={
                'verbose_name': 'Quick Reply Option',
                'verbose_name_plural': 'Quick Reply Options',
                'ordering': ['node', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='instagram.flownode')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_messages', to='instagram.flowsession')),
            ],
            options={
                'verbose_name': 'Scheduled Message',
                'verbose_name_plural': 'Scheduled Messages',
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.DeleteModel(
            name='InstagramAutomation',
        ),
        migrations.DeleteModel(
            name='InstagramCommentEvent',
        ),
        migrations.AddIndex(
            model_name='flowsession',
            index=models.Index(fields=['instagram_scoped_id'], name='instagram_f_instagr_1aca28_idx'),
        ),
        migrations.AddIndex(
            model_name='flowsession',
            index=models.Index(fields=['status'], name='instagram_f_status_e8e6a6_idx'),
        ),
        migrations.AddIndex(
            model_name='collectedlead',
            index=models.Index(fields=['instagram_scoped_id'], name='instagram_c_instagr_085a04_idx'),
        ),
        migrations.AddIndex(
            model_name='collectedlead',
            index=models.Index(fields=['user', 'created_at'], name='instagram_c_user_id_757490_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledmessage',
            index=models.Index(fields=['status', 'scheduled_for'], name='instagram_s_status_155cd2_idx'),
        ),
    ]
