# Generated by Django 6.0 on 2026-01-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0007_dm_flow_builder'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='scheduledmessage',
            name='instagram_s_status_155cd2_idx',
        ),
        migrations.AlterField(
            model_name='flowexecutionlog',
            name='action',
            field=models.CharField(choices=[('flow_started', 'Flow Started'), ('node_executed', 'Node Executed'), ('message_sent', 'Message Sent'), ('comment_replied', 'Comment Replied'), ('quick_reply_received', 'Quick Reply Received'), ('text_reply_received', 'Text Reply Received'), ('condition_checked', 'Condition Checked'), ('data_collected', 'Data Collected'), ('flow_completed', 'Flow Completed'), ('error', 'Error')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flownode',
            name='node_type',
            field=models.CharField(choices=[('comment_reply', 'Comment Reply'), ('message_text', 'Text Message'), ('message_quick_reply', 'Quick Reply Message'), ('message_link', 'Link Message'), ('message_media', 'Media Message'), ('condition_follower', 'Follower Check'), ('collect_data', 'Collect Data')], max_length=30),
        ),
        migrations.AlterField(
            model_name='flowsession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('waiting_reply', 'Waiting for Reply'), ('completed', 'Completed'), ('expired', 'Expired'), ('error', 'Error')], default='active', max_length=20),
        ),
        migrations.DeleteModel(
            name='ScheduledMessage',
        ),
    ]
