# Generated by Django 6.0 on 2026-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_remove_scheduled_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flownode',
            name='node_type',
            field=models.CharField(choices=[('comment_reply', 'Comment Reply'), ('message_text', 'Text Message'), ('message_quick_reply', 'Quick Reply Message'), ('message_button_template', 'Button Template'), ('message_link', 'Link Message'), ('message_media', 'Media Message'), ('condition_follower', 'Follower Check'), ('collect_data', 'Collect Data')], max_length=30),
        ),
    ]
