# Generated by Django 6.0 on 2026-01-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_add_condition_user_interacted_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('lead_gen', 'Lead Generation'), ('follow_gate', 'Follow Gate'), ('quiz', 'Quiz / Survey'), ('giveaway', 'Giveaway'), ('link_delivery', 'Link Delivery'), ('other', 'Other')], default='other', max_length=20)),
                ('nodes_json', models.JSONField(help_text='JSON array of node configurations')),
                ('icon', models.CharField(default='bi-lightning', help_text='Bootstrap icon class (e.g., bi-lightning, bi-person-check)', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Flow Template',
                'verbose_name_plural': 'Flow Templates',
                'ordering': ['order', 'title'],
            },
        ),
    ]
