# Generated by Django 6.0 on 2026-01-29 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_alter_flownode_node_type_knowledgebase_knowledgeitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_type', models.CharField(choices=[('dm', 'Direct Message'), ('comment_reply', 'Comment Reply')], max_length=20)),
                ('endpoint', models.CharField(max_length=255)),
                ('recipient_id', models.CharField(blank=True, max_length=255)),
                ('success', models.BooleanField(default=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_call_logs', to='instagram.instagramaccount')),
            ],
            options={
                'verbose_name': 'API Call Log',
                'verbose_name_plural': 'API Call Logs',
                'indexes': [models.Index(fields=['account', 'sent_at'], name='instagram_a_account_cf9793_idx'), models.Index(fields=['account', 'call_type', 'sent_at'], name='instagram_a_account_2b58d7_idx')],
            },
        ),
    ]
