# Generated by Django 6.0 on 2026-01-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_api_call_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueuedFlowTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('comment', 'Comment')], default='comment', max_length=20)),
                ('instagram_event_id', models.CharField(max_length=255)),
                ('trigger_context', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_flow_triggers', to='instagram.instagramaccount')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queued_triggers', to='instagram.dmflow')),
            ],
            options={
                'verbose_name': 'Queued Flow Trigger',
                'verbose_name_plural': 'Queued Flow Triggers',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['account', 'status', 'created_at'], name='instagram_q_account_a1b2c3_idx')],
                'unique_together': {('account', 'instagram_event_id')},
            },
        ),
    ]
