# Generated by Django 6.0 on 2026-01-29 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_queued_flow_trigger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='queuedflowtrigger',
            new_name='instagram_q_account_791738_idx',
            old_name='instagram_q_account_a1b2c3_idx',
        ),
    ]
