# Generated by Django 6.0 on 2026-01-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0016_rename_instagram_q_account_a1b2c3_idx_instagram_q_account_791738_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmflow',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
