# Generated by Django 6.0 on 2026-02-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0017_add_metadata_to_dmflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramaccount',
            name='total_comments_replied',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instagramaccount',
            name='total_dms_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flowtemplate',
            name='category',
            field=models.CharField(choices=[('follow_gate', 'Follow Gate'), ('quiz', 'Quiz / Survey'), ('giveaway', 'Giveaway'), ('link_delivery', 'Link Delivery'), ('other', 'Other'), ('lead_gen', 'Lead Generation')], default='other', max_length=20),
        ),
    ]
