# Generated by Django 6.0 on 2026-02-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0018_instagramaccount_total_comments_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedflowtrigger',
            name='auto_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
