# Generated by Django 6.0 on 2026-02-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0019_queuedflowtrigger_auto_eligible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroppedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_username', models.CharField(blank=True, max_length=255)),
                ('comment_text', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropped_messages', to='instagram.instagramaccount')),
            ],
            options={
                'verbose_name': 'Dropped Message',
                'verbose_name_plural': 'Dropped Messages',
                'ordering': ['-created_at'],
            },
        ),
    ]
