# Generated by Django 6.0 on 2026-02-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0020_droppedmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmflow',
            name='deactivated_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('system', 'System')], default=None, max_length=10, null=True),
        ),
    ]
